# Generated by Django 2.0.6 on 2021-10-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('pk_tabla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('computo', models.CharField(max_length=20)),
            ],
        ),
    ]
