# Generated by Django 2.0.6 on 2021-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla',
            name='computo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
